document.writeln(" <div><a href=\"/default/img/mobile.html\"><img  src=\"/default/img/mobile-jaw-crusher-1.gif\" alt=\"Mobile Jaw Crusher\" /></a>");
document.writeln("                <a href=\"/default/img/mobile.html\"><h2>Mobile Crusher</h2></a>");
document.writeln("                <p> The mobile crushing plant has the advantages of easy transportation, low transportation cost, flexible configuration, convenient maintenance etc. It can be operated as independent units, or as two-stage crushing plant with primary and secondary crushing, or as three stage crushing plant according to different clients\' requirements.</p>");
document.writeln("                <p style=\"border-top:1px dashed #666; margin-left:12px; width:300px; color:#33C;\"><strong>Click here to get online consultation.</strong></p>");
document.writeln("</p><a rel=\"nofollow\" href=\"javascript:void(0);\" onclick=\"openZoosUrl(\'chatwin\')\"><img src=\"/default/img/order.gif\" style=\"width:280px; height:41px; margin-top:10px;\"></a></p>");
document.writeln("            </div>");
document.writeln("                      ");
document.writeln("             <div><a href=\"/default/img/stonecrusher.html\"><img  src=\"/default/img/pew-jaw-crusher.gif\" alt=\"PEW Series Jaw Crusher\" /></a>");
document.writeln("                <h2><a href=\"/default/img/stonecrusher.html\">Stone Crusher</a></h2>");
document.writeln("                <p> KEFID has been serving the stone crushing & grinding industry for over 20 years, it is one of the most famous stone and mineral processing company in the world. KEFID has a group of bridle-wise workers and experienced on-site engineers, who ensure every set of equipments is of high performance and high reliability.</p>");
document.writeln("               <p style=\"border-top:1px dashed #666; margin-left:12px; width:300px;color:#33C;\"><strong>Click here to get online consultation.</strong></p>");
document.writeln("</p><a rel=\"nofollow\" href=\"javascript:void(0);\" onclick=\"openZoosUrl(\'chatwin\')\"><img src=\"/default/img/order.gif\" style=\"width:280px; height:41px; margin-top:10px;\"></a></p>");
document.writeln("            </div>");
document.writeln("            ");
document.writeln("             <div><a href=\"/default/img/grinding.html\"><img  src=\"/default/img/vertical-coll-mill.gif\" alt=\"LM Vertical Grinding Mills\" /></a>");
document.writeln("                <h2><a href=\"/default/img/grinding.html\">Grinding Mill</a></h2>");
document.writeln("                <p> Grinding is the required powdering or pulverizing process when final size of below 2 mm is needed. KEFID can provide the proper grinding measure to all kinds of methods and application, such as XZM series ultrafine mill\'s output size can reach 2500mesh (5um)</p>");
document.writeln("                <p style=\"border-top:1px dashed #666; margin-left:12px; width:300px;color:#33C;\"><strong>Click here to get online consultation.</strong></p>");
document.writeln("</p><a rel=\"nofollow\" href=\"javascript:void(0);\" onclick=\"openZoosUrl(\'chatwin\')\"><img src=\"/default/img/order.gif\" style=\"width:280px; height:41px; margin-top:10px;\"></a></p>");
document.writeln("            </div>");
document.writeln("            ");
document.writeln("             <div><a href=\"/default/img/beneficiation.html\"><img  src=\"/default/img/flotation-machine.gif\" alt=\"Flotation Machine\" /></a>");
document.writeln("                <h2><a href=\"/default/img/beneficiation.html\">Beneficiation Equipments</a></h2>");
document.writeln("                <p> KEFID screen can separate the stuff of different size range. It is the most general means of size control in aggregates processing. Washing machine is a kind of cleaning equipment of international advanced level for sand and slag pellets, it is developed on the basis of introducing foreign outstanding technology of the same kind of products.</p>");
document.writeln("                <p style=\"border-top:1px dashed #666; margin-left:12px; width:300px;color:#33C;\"><strong>Click here to get online consultation.</strong></p>");
document.writeln("</p><a rel=\"nofollow\" href=\"javascript:void(0);\" onclick=\"openZoosUrl(\'chatwin\')\"><img src=\"/default/img/order.gif\" style=\"width:280px; height:41px; margin-top:10px;\"></a></p>");
document.writeln("            </div>");
document.writeln("                ");
document.writeln("               <div><a href=\"/default/img/feeding.html\"><img  src=\"/default/img/belt-conveyor.gif\" alt=\"Belt Conveyor\"></a>");
document.writeln("                <h2><a href=\"/default/img/feeding.html\">Feeding and Conveying Machine</a></h2>");
document.writeln("                <p> Feeders are necessary when we need to deliver a mass flow of stone and minerals, especially in complete crushing plant. And conveying is by far the main means to transport material in stone processing, Kefid offers the suitable solution to satisfy customer\'s needs in feeding and conveying.</p>");
document.writeln("                <p style=\"border-top:1px dashed #666; margin-left:12px; width:300px;color:#33C;\"><strong>Click here to get online consultation.</strong></p>");
document.writeln("</p><a rel=\"nofollow\" href=\"javascript:void(0);\" onclick=\"openZoosUrl(\'chatwin\')\"><img src=\"/default/img/order.gif\" style=\"width:280px; height:41px; margin-top:10px;\"></a></p>");
document.writeln("            </div>   ");