document.writeln("        	<div id=\"taicp-title\" style=\"margin-top:19px;\">PRODUCTS <span>LIST</span></div>");
document.writeln("            <div id=\"tccp-neirong\">");
document.writeln("            	<ul>");
document.writeln("                   <li><a href=\"/default/img/stonecrusher.html\" rel=\"nofollow\" class=\"white\">Stone Crusher</a></li>");
document.writeln("                        <li><a href=\"/default/img/mobile.html\" rel=\"nofollow\" class=\"white\">Mobile Crusher</a></li>");
document.writeln("                        <li><a href=\"/default/img/grinding.html\" rel=\"nofollow\" class=\"white\">Grinding Mill</a></li>");
document.writeln("                        <li><a href=\"/default/img/feeding.html\" rel=\"nofollow\" class=\"white\">Feeding& Conveying</a></li>");
document.writeln("                        <li><a href=\"/default/img/beneficiation.html\" rel=\"nofollow\" class=\"white\">Beneficiation Equipments</a></li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("");
document.writeln("          ");
document.writeln("    <h3><span>Chat Online</span></h3><a href=\"javascript:void(0)\" onclick=\"openZoosUrl()\" target=\"_top\"><img src=\"/default/img/chat.jpg\" class=\"chat\" alt=\"chat online\"></a>");
document.writeln("    <h3><span>Inquiry</span></h3>");
document.writeln("    <form id=\"inquiry\" method=\"post\" name=\"form\" action=\"http://data.kefid.com/Action.asp\" onsubmit=\"return(CheckfootInput())\">");
document.writeln("    <p>Please fill in your name and your message and do not forget mail and/or phone if you like to be contacted. Please note that you do not need to have a mail programme to use this function.</p>");
document.writeln("    <div>");
document.writeln("        <!-- Text input-->");
document.writeln("        <label for=\"name\">Name:<span>*</span></label>");
document.writeln("        <input name=\"userName\" style=\"color: rgb(153, 153, 153);\" onfocus=\"if(value==\'As: Mario\'){value=\'\';this.style.color=\'#000\';};\" onblur=\"if(value==\'\'){value=\'As: Mario\';this.style.color=\'#999\';};\" value=\"As: Mario\" size=\"25\" type=\"text\">");
document.writeln("    </div>");
document.writeln("    <div>");
document.writeln("        <!-- Text input-->");
document.writeln("        <label for=\"input01\">Email:<span>*</span></label>");
document.writeln("        <input name=\"userEMail\" style=\"color: rgb(153, 153, 153);\" onfocus=\"if(value==\'As: sample@isp.com\'){value=\'\';this.style.color=\'#000\';};\" onblur=\"if(value==\'\'){value=\'As: sample@isp.com\';this.style.color=\'#999\';};\" value=\"As: sample@isp.com\" size=\"25\" maxlength=\"50\" type=\"text\">");
document.writeln("    </div>");
document.writeln("    <div>");
document.writeln("        <!-- Textarea -->");
document.writeln("        <label>Message:<span>*</span></label>");
document.writeln("        <textarea name=\"Message\" cols=\"45\" rows=\"6\" style=\"color: rgb(153, 153, 153);\" onfocus=\"if(value==\'As: output size like 0-10,10-15, 15-20 mm for crushing or 75 microns ( 200 meshes) for mill machine and other requirements.\'){value=\'\';this.style.color=\'#000\';};\" onblur=\"if(value==\'\'){value=\'As: output size like 0-10,10-15, 15-20 mm for crushing or 75 microns ( 200 meshes) for mill machine and other requirements.\';this.style.color=\'#999\';};\">As: output size like 0-10,10-15, 15-20 mm for crushing or 75 microns ( 200 meshes) for mill machine and other requirements.</textarea>");
document.writeln("    </div>");
document.writeln("    <div>");
document.writeln("        <label>Products:</label>");
document.writeln("        <select name=\"product\">");
document.writeln("            <option selected=\"selected\" value=\"\" style=\"color: rgb(255, 0, 0); font-weight: bold;\">Please Select!</option>");
document.writeln("            <option value=\"Mobile crushing plant\">Mobile Crusher</option>");
document.writeln("            <option value=\"LM Vertical Grinding Mill\">Vertical Mill</option>");
document.writeln("            <option value=\"Jaw Crusher\">Jaw Crusher</option>");
document.writeln("            <option value=\"Cone Crusher\">Cone Crusher</option>");
document.writeln("            <option value=\"MTW European Grinding Machine\">MTW European Grinding Machine</option>");
document.writeln("            <option value=\"Ultrafine Mill\">Ultrafine Mill</option>");
document.writeln("            <option value=\"Impact Crusher\">Impact Crusher</option>");
document.writeln("            <option value=\"VSI Crusher\">VSI Crusher</option>");
document.writeln("            <option value=\"Hydraulic Cylinder Cone Crusher\">Hydraulic Cylinder Cone Crusher</option>");
document.writeln("            <option value=\"Sand Washing Machine\">Sand Washing Machine</option>");
document.writeln("            <option value=\"Vibrating Screen\">Vibrating Screen</option>");
document.writeln("            <option value=\"Vibrating Feeder\">Vibrating Feeder</option>");
document.writeln("            <option value=\"Belt Conveyor\">Belt Conveyor</option>");
document.writeln("            <option value=\"Stone processing production line\">Stone processing production line</option>");
document.writeln("            <option value=\"Industrial milling production line\">Industrial milling production line</option>");
document.writeln("            <option value=\"Beneficiation Production Line\">Beneficiation Production Line</option>");
document.writeln("            <option value=\"Not Sure\" style=\"color: rgb(255, 0, 0); font-weight: bold;\">Not Sure !</option>");
document.writeln("        </select>");
document.writeln("    </div>");
document.writeln("    <div>");
document.writeln("        <label>Application:</label>");
document.writeln("        <!-- Multiple Checkboxes -->");
document.writeln("        <select name=\"mType\" id=\"Application\" onchange=\"checkapplication()\">");
document.writeln("       <option>Select</option>");
document.writeln("      <option value=\"Limestone\">Limestone</option>");
document.writeln("      <option value=\"Granite\">Granite</option>");
document.writeln("      <option value=\"Basalt\">Basalt</option>");
document.writeln("      <option value=\"Iron ore\">Iron ore</option>");
document.writeln("      <option value=\"Gold\">Gold</option>");
document.writeln("      <option value=\"Barite\">Barite</option>");
document.writeln("      <option value=\"Marble\">Marble</option>");
document.writeln("      <option value=\"Other\">Other</option></select>");
document.writeln("    </div>");
document.writeln("    <div>");
document.writeln("        <!-- Text input-->");
document.writeln("        <label for=\"phone\">Phone:</label>");
document.writeln("        <input name=\"userTel\" style=\"color: rgb(153, 153, 153);\" onfocus=\"if(value==\'As: 0086-371-56719929\'){value=\'\';this.style.color=\'#000\';};\" onblur=\"if(value==\'\'){value=\'As: 0086-371-56719929\';this.style.color=\'#999\';};\" value=\"As: 0086-371-56719929\" size=\"25\" type=\"text\">");
document.writeln("    </div>");
document.writeln("    <div>");
document.writeln("        <!-- Button -->");
document.writeln("        <input value=\"Submit\" type=\"submit\">");
document.writeln("    </div>");
document.writeln("</form>");
document.writeln("<script type=\"text/javascript\">");
document.writeln("function is_number(str) ");
document.writeln("{");
document.writeln("	exp = /[^0-9 .+()-]/g;");
document.writeln("	if (str.search(exp) != -1) ");
document.writeln("	{");
document.writeln("		return false;");
document.writeln("	}");
document.writeln("	return true;");
document.writeln("}");
document.writeln("			");
document.writeln("function is_email(str) ");
document.writeln("{");
document.writeln("	if ((str.indexOf(\"@\") == -1) || (str.indexOf(\".\") == -1)) ");
document.writeln("	{");
document.writeln("		return false;");
document.writeln("	}");
document.writeln("	return true;");
document.writeln("}");
document.writeln("				");
document.writeln("function CheckfootInput()");
document.writeln("{");
document.writeln("	if(document.form.name.value==\'\'||document.form.name.value==\'As: Mario\')");
document.writeln("	{");
document.writeln("		alert(\"Please Write Your Name ^_^\");");
document.writeln("		document.form.name.focus();");
document.writeln("		return false;");
document.writeln("	}");
document.writeln("				");
document.writeln("	if(document.form.email.value==\'\'||document.form.email.value==\'As: sample@isp.com\'||!is_email(document.form.email.value))");
document.writeln("	{");
document.writeln("		alert(\"Please Write Your Email ^_^\");");
document.writeln("		document.form.email.focus();");
document.writeln("		return false;");
document.writeln("	}");
document.writeln("				");
document.writeln("	if(document.form.content.value==\'\'||document.form.content.value==\'As: output size like 0-10,10-15, 15-20 mm for crushing or 75 microns ( 200 meshes) for mill machine and other requirements.\')");
document.writeln("	{");
document.writeln("		alert(\"Please Write Your Message ^_^\");");
document.writeln("		document.form.content.focus();");
document.writeln("		return false;");
document.writeln("	}");
document.writeln("				");
document.writeln("	if(document.form.capacity.value==\'As: 20 TPH\')");
document.writeln("	{");
document.writeln("		document.form.capacity.value=\'\';");
document.writeln("	}");
document.writeln("				");
document.writeln("	if(document.form.title.value==\'As: Marble\')");
document.writeln("	{");
document.writeln("		document.form.title.value=\'\';");
document.writeln("	}");
document.writeln("				");
document.writeln("	if(document.form.phone.value==\'As: 0086-371-56719929\')");
document.writeln("	{");
document.writeln("		document.form.phone.value = \'\';");
document.writeln("	}");
document.writeln("				");
document.writeln("	return true;");
document.writeln("}");
document.writeln("</script>  ");