document.writeln(" <div id=\"top_bg\">");
document.writeln("    <div id=\"top\">");
document.writeln("      <a href=\"/\" class=\"index\"></a>");
document.writeln("      <!--navbegin-->");
document.writeln("      <div class=\"nav\">");
document.writeln("        <ul>");
document.writeln("          <li>");
document.writeln("            <a href=\"/\" class=\"home\">HOME</a>");
document.writeln("          </li>");
document.writeln("          <li>");
document.writeln("            <a href=\"/default/static/about.html\" rel=\"nofollow\">ABOUT US</a>");
document.writeln("          </li>");
document.writeln("          <li>");
document.writeln("            <a href=\"/default/static/products.html\" rel=\"nofollow\">PRODUCTS</a>");
document.writeln("          </li>");
document.writeln("          <li>");
document.writeln("            <a href=\"/default/static/contact.html\" rel=\"nofollow\">CONTACT US</a>");
document.writeln("          </li>");
document.writeln("          <li>");
document.writeln("            <a href=\"/default/static/service.html\" rel=\"nofollow\">SERVICE</a>");
document.writeln("          </li>");
document.writeln("        </ul>");
document.writeln("      </div>");
document.writeln("      <!--navover-->");
document.writeln("    </div>");
document.writeln("  </div>");
document.writeln("  <div id=\"banner\">");
document.writeln("    <a rel=\"nofollow\" href=\"javascript:void(0);\"");
document.writeln("      onclick=\"openZoosUrl(\'chatwin\')\">");
document.writeln("      <img src=\"/default/img/banner.jpg\"");
document.writeln("        style=\"width: 985px; height: 313px; margin-top: 8px; margin-left: 8px;\" />");
document.writeln("    </a>");
document.writeln("  </div>");